<?php
echo '<!DOCTYPE html>';
echo '<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->';
echo '<html lang="en" dir="ltr">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title> Responsive Contact Us Form  | CodingLab </title>';
echo '<link rel="stylesheet" href="style.css">';
echo '<!-- Fontawesome CDN Link -->';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="content">';
echo '<div class="left-side">';
echo '<div class="address details">';
echo '<i class="fas fa-map-marker-alt"></i>';
echo '<div class="topic">Address</div>';
echo '<div class="text-one">Surkhet, NP12</div>';
echo '<div class="text-two">Birendranagar 06</div>';
echo '</div>';
echo '<div class="phone details">';
echo '<i class="fas fa-phone-alt"></i>';
echo '<div class="topic">Phone</div>';
echo '<div class="text-one">+91 9310519210</div>';
echo '<div class="text-two">+91 8076654886</div>';
echo '<div class="text-three">+91 8766393891</div>';
echo '';
echo '</div>';
echo '<div class="email details">';
echo '<i class="fas fa-envelope"></i>';
echo '<div class="topic">Email</div>';
echo '<div class="text-one">simran033btcsai20@gmail.com</div>';
echo '<div class="text-two">simran065btcsai20@igdtuw.ac.in</div>';
echo '<div class="text-two">srishti060btcsai20@igdtuw.ac.in</div>';
echo '</div>';
echo '</div>';
echo '<div class="right-side">';
echo '<div class="topic-text">Send us a message</div>';
echo '<p>If you have any work from me or any types of quries related to my tutorial, you can send me message from here. It's my pleasure to help you.</p>';
echo '<form action="#">';
echo '<div class="input-box">';
echo '<input type="text" placeholder="Enter your name">';
echo '</div>';
echo '<div class="input-box">';
echo '<input type="text" placeholder="Enter your email">';
echo '</div>';
echo '<div class="input-box message-box">';
echo '<textarea placeholder="Enter your message"></textarea>';
echo '</div>';
echo '<div class="button">';
echo '<input type="button" value="Send Now" >';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>